version: '3.7'

services:
  redmine:
    image: redmine:4.1
    container_name: redmine
    volumes:
      - ./volumes/files:/usr/src/redmine/files
      - ./volumes/plugins:/usr/src/redmine/plugins
      - ./volumes/public/themes:/usr/src/redmine/public/themes
      - ./volumes/sqlite:/usr/src/redmine/sqlite
    ports:
      - 3000:3000
    environment:
      - TZ=Asia/Tokyo
    restart: unless-stopped
